# Generated by Django 1.11.13 on 2018-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_gift_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='You can use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown</a>.',
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link"
            ),
        ),
    ]
