[tool.isort]
profile = "black"

[tool.ruff]
ignore = [
  "TRY003",
  "EM101",
  "PTH",
  "S105",
  "ARG001",
  "RUF012",
  "PT",
  "D211",
  "D212",
  "D100",
  "D104",
  "D101",
  "D103",
  "D102",
  "D105",
  "D106",
  "DJ001",
  "ANN"
]
output-format = "github"
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 16

[tool.ruff.per-file-ignores]
"wishlist/migrations/0001_initial.py" = ["E501"]
"wishlist/migrations/0003_auto_20181009_1330.py" = ["E501"]
