name: ruff

on:
  push:
    branches-ignore:
    - dependabot/**
    - weblate
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/cache@v4.1.2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-lint.txt
    - name: Run ruff
      run: |
        pre-commit run ruff --all
