name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
        - '3.11'
        - '3.12'
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Cache pip
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo apt-get update
    - run: sudo apt-get install -y gettext
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Compile MO files
      run: ./manage.py compilemessages
    - name: Django checks
      run: ./manage.py check
    - name: Test with Django
      run: coverage run ./manage.py test
    - name: Coverage
      run: |
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        name: Python ${{ matrix.python-version }}
